-- =============================================================================
-- Migration: Pre-computed RAG Knowledge Cache
-- IPSAS Practitioner Advisor — offline-generated context packets
--
-- Run this in Supabase SQL Editor AFTER migration-openrouter-config.sql.
--
-- What this adds:
--   1. rag_knowledge_cache      — one row per IPSAS standard or topic cluster;
--                                 stores pre-retrieved ChromaDB chunks so that
--                                 query time hits Supabase instead of ChromaDB
--   2. rag_cache_invalidation_log — manual audit trail for cache rebuild events
--   3. rag_cache_build_log        — records each run of the build script
-- =============================================================================


-- ============================================================================
-- TABLE: rag_knowledge_cache
-- ============================================================================
-- One row per IPSAS standard or topic cluster (~80 rows total).
-- Populated offline by scripts/build-rag-cache.py.
-- Read at query time by the Next.js API route to inject context into the LLM.

create table if not exists rag_knowledge_cache (
  id                   uuid        primary key default uuid_generate_v4(),

  -- Unique key used for lookups. Two formats:
  --   standard entry:     'IPSAS-23', 'IPSAS-17', 'C4-Cash-Basis'
  --   topic cluster:      'topic-revenue-non-exchange', 'topic-ppe'
  cache_key            text        not null unique,

  -- Human-readable label shown in logs and debug output
  label                text        not null,

  -- 'standard'     — one per IPSAS standard ID (from ipsas-standards-index.yaml)
  -- 'topic_cluster'— one per topic spine item (covers multiple related standards)
  entry_type           text        not null
                         check (entry_type in ('standard', 'topic_cluster')),

  -- Which IPSAS standard IDs this packet covers.
  -- Standard entry:      ['IPSAS-23']
  -- Topic cluster entry: ['IPSAS-9', 'IPSAS-23', 'IPSAS-47']
  standard_ids         text[]      not null default '{}',

  -- Which pathway this entry applies to
  pathway              text        not null default 'accrual'
                         check (pathway in ('accrual', 'cash-basis', 'both')),

  -- The pre-retrieved ChromaDB chunks for this standard/topic.
  -- Stored as a JSONB array; each element: { "text": "...", "source": "IPSAS-23", "score": 0.87 }
  -- At query time, these are injected into the LLM system prompt as context.
  raw_chunks           jsonb       not null default '[]'::jsonb,

  -- Optional: LLM-synthesised compact summary (~400 words).
  -- Null at MVP; generated by the build script when --synthesise flag is passed.
  -- When present, this is used instead of the raw chunks (more compact, faster).
  synthesised_summary  text,

  -- Keywords used for query-time matching.
  -- When a user submits a question, their text is checked against these keywords.
  -- Populated from the standards index (topics + work_areas fields).
  keywords             text[]      not null default '{}',

  -- IPSAS effective date of the primary standard — used to exclude
  -- not-yet-effective standards from being injected into the LLM context
  effective_date       date,

  -- Mirrors ipsas_regulation_metadata.status — used to skip superseded entries
  standard_status      text        default 'current'
                         check (standard_status in ('current', 'superseded', 'not_yet_effective')),

  -- When this packet was last generated (used to spot stale entries)
  generated_at         timestamptz not null default now(),

  -- The ChromaDB query that produced this packet (for debugging and regeneration).
  -- Format: { "query_text": "...", "n_results": 15, "filter": {...} }
  generation_query     jsonb       default '{}'::jsonb,

  -- How many ChromaDB chunks were available for this standard at build time.
  -- Low values indicate thin coverage — that standard may need more PDF content.
  source_chunk_count   integer     default 0,

  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

-- Primary lookup: cache_key → packet (O(1), used on every query)
create unique index if not exists rag_cache_key
  on rag_knowledge_cache(cache_key);

-- Array index for "which packets cover standard X?" lookups
create index if not exists rag_cache_standard_ids
  on rag_knowledge_cache using gin(standard_ids);

-- Array index for keyword-based matching
create index if not exists rag_cache_keywords
  on rag_knowledge_cache using gin(keywords);

-- Filter index for pathway
create index if not exists rag_cache_pathway
  on rag_knowledge_cache(pathway);

-- Staleness check index
create index if not exists rag_cache_generated_at
  on rag_knowledge_cache(generated_at);

-- RLS: all approved users can read (it is reference data, not personal data).
-- Only the service role can write (the Python build script uses the service role key).
alter table rag_knowledge_cache enable row level security;

create policy "Approved users can read the knowledge cache"
  on rag_knowledge_cache for select
  using (is_approved());

-- No INSERT/UPDATE/DELETE policy for regular users —
-- the Python script uses the service role key which bypasses RLS automatically.


-- ============================================================================
-- TABLE: rag_cache_invalidation_log
-- ============================================================================
-- Manual audit trail for events that require a cache rebuild.
-- Insert a row here before running the build script with --only or --rebuild,
-- then mark resolved = true after the rebuild completes.
--
-- This is NOT automated — it is a deliberate manual process.
-- Keeping invalidation manual keeps the system predictable.

create table if not exists rag_cache_invalidation_log (
  id           uuid        primary key default uuid_generate_v4(),

  -- Which cache entry needs refreshing (matches cache_key in rag_knowledge_cache)
  cache_key    text        not null,

  -- Why this entry needs rebuilding, e.g.:
  --   'New 2025 handbook PDF added — IPSAS 47 chapter updated'
  --   'Standard amended — IPSAS 23 paragraph numbering changed'
  reason       text        not null,

  -- Who/what triggered the invalidation
  triggered_by text        default 'manual',

  -- Set to true after the cache entry has been rebuilt
  resolved     boolean     default false,

  created_at   timestamptz not null default now(),
  resolved_at  timestamptz
);

create index if not exists rag_cache_inval_key
  on rag_cache_invalidation_log(cache_key);

create index if not exists rag_cache_inval_unresolved
  on rag_cache_invalidation_log(resolved) where resolved = false;

alter table rag_cache_invalidation_log enable row level security;

-- Approved users can log an invalidation event (e.g. admin noting a new PDF)
create policy "Approved users can insert invalidation records"
  on rag_cache_invalidation_log for insert
  with check (is_approved());

create policy "Approved users can read invalidation log"
  on rag_cache_invalidation_log for select
  using (is_approved());

-- Only admins can mark records as resolved
create policy "Admins can update invalidation records"
  on rag_cache_invalidation_log for update
  using (is_admin());


-- ============================================================================
-- TABLE: rag_cache_build_log
-- ============================================================================
-- Records each run of the build script.
-- Written by the Python script using the service role key.
-- Useful for knowing what was built when and catching script failures.

create table if not exists rag_cache_build_log (
  id              uuid        primary key default uuid_generate_v4(),

  started_at      timestamptz not null default now(),
  completed_at    timestamptz,

  -- Counts from this run
  entries_built   integer     default 0,   -- new entries written or updated
  entries_skipped integer     default 0,   -- already up to date, skipped
  entries_failed  integer     default 0,   -- errors during build

  -- 'incremental'  — skip already-cached entries (default)
  -- 'full_rebuild' — rebuild all entries even if cached
  -- 'selective'    — rebuild only specific entries passed via --only flag
  mode            text        default 'incremental'
                    check (mode in ('incremental', 'full_rebuild', 'selective')),

  -- Optional notes, e.g. which standards were rebuilt in selective mode
  notes           text,

  -- Set to true when the script completes without any failures
  success         boolean     default false
);

alter table rag_cache_build_log enable row level security;

-- Build log is written by the service role (no INSERT policy needed).
-- Admins can read it to check build history.
create policy "Admins can read build log"
  on rag_cache_build_log for select
  using (is_admin());


-- ============================================================================
-- USEFUL QUERIES
-- ============================================================================
-- Run these in the Supabase SQL Editor to monitor cache health:

-- 1. Count entries by type and pathway:
-- select entry_type, pathway, count(*), avg(source_chunk_count) as avg_chunks
-- from rag_knowledge_cache
-- group by entry_type, pathway
-- order by entry_type, pathway;

-- 2. Find stale entries (not rebuilt in 90 days):
-- select cache_key, label, generated_at
-- from rag_knowledge_cache
-- where generated_at < now() - interval '90 days'
-- order by generated_at asc;

-- 3. Find thin entries (fewer than 5 chunks — may need more PDF content):
-- select cache_key, label, source_chunk_count
-- from rag_knowledge_cache
-- where source_chunk_count < 5
-- order by source_chunk_count asc;

-- 4. Unresolved invalidation events:
-- select * from rag_cache_invalidation_log where resolved = false order by created_at desc;

-- 5. Most recent build runs:
-- select * from rag_cache_build_log order by started_at desc limit 10;
