-- Migration: pgvector-backed IPSAS chunks table
-- Replaces the keyword-match rag_knowledge_cache approach with a real
-- vector-similarity retrieval layer.
--
-- Embedding model: OpenAI text-embedding-3-small, 1536 dimensions.
--   - Higher quality than the prior ChromaDB default (all-MiniLM-L6-v2, 384-dim)
--     on retrieval benchmarks, especially for technical / cross-paragraph queries.
--   - Bulk re-embed cost (~21k chunks): ~$0.20 one-time
--   - Per-query cost: <$0.0001
--   - Embeddings are generated by scripts/migrate-chroma-to-supabase.py and the
--     server-side embedQuery() in src/lib/advisor/embeddings.ts. Both must use
--     the same model — switching models requires re-embedding the whole corpus.
--
-- Source-tier weighting: each chunk records its origin folder so retrieval
-- can re-rank by the documentation hierarchy from CLAUDE.md
--   (1=Regulations, 2=Standards, 3=Study Guides, 4=Guidance, 5=Gov-Specific).
--
-- Effective-date filtering: standard_id joins to ipsas_regulation_metadata
-- so the retrieval RPC can exclude superseded standards.

create extension if not exists vector;

create table if not exists public.ipsas_chunks (
  id uuid primary key default gen_random_uuid(),

  -- Provenance — keys back to source document
  source_pdf text,                          -- e.g. "2025_IPSASB_HB_Volume_1_0.pdf"
  source_url text,                          -- for web-sourced chunks
  page_number integer,
  chunk_index integer,                      -- ordinal within source

  -- IPSAS metadata (filterable)
  standard_id text,                         -- e.g. "IPSAS-23"
  standards text[],                         -- when chunk references multiple standards
  pathway text,                             -- 'accrual' | 'cash-basis' | 'both'
  audience text default 'both',             -- 'student' | 'practitioner' | 'both'
  topics text[],                            -- e.g. {"revenue", "non-exchange"}
  work_areas text[],                        -- e.g. {"AP", "GL"}
  jurisdiction_code text,                   -- e.g. 'SIG' for Solomon Islands; null = universal

  -- Hierarchy (per Documentation/Accounting-documentation-hierarchy.md)
  source_tier integer not null default 4    -- lower = higher priority
    check (source_tier between 1 and 6),

  -- Content
  text text not null,
  text_tokens integer,                      -- approximate; for prompt budgeting

  -- Embedding (OpenAI text-embedding-3-small — 1536-dim)
  embedding vector(1536),

  -- Timestamps
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Indexes ---------------------------------------------------------------------

-- Vector similarity (HNSW, cosine distance — matches OpenAI default normalisation)
-- Note: HNSW max dim is 2000 in pgvector; 1536 is well under.
create index if not exists ipsas_chunks_embedding_hnsw
  on public.ipsas_chunks
  using hnsw (embedding vector_cosine_ops);

-- Common filters
create index if not exists ipsas_chunks_standard_id_idx
  on public.ipsas_chunks (standard_id);

create index if not exists ipsas_chunks_pathway_idx
  on public.ipsas_chunks (pathway);

create index if not exists ipsas_chunks_jurisdiction_idx
  on public.ipsas_chunks (jurisdiction_code);

create index if not exists ipsas_chunks_source_tier_idx
  on public.ipsas_chunks (source_tier);

-- GIN for array columns
create index if not exists ipsas_chunks_topics_gin
  on public.ipsas_chunks using gin (topics);

create index if not exists ipsas_chunks_work_areas_gin
  on public.ipsas_chunks using gin (work_areas);

create index if not exists ipsas_chunks_standards_gin
  on public.ipsas_chunks using gin (standards);

-- RLS -------------------------------------------------------------------------

alter table public.ipsas_chunks enable row level security;

-- Approved users can read chunks (the advisor server action queries this)
create policy "approved users read ipsas chunks"
  on public.ipsas_chunks
  for select
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
        and profiles.account_status = 'approved'
    )
  );

-- Writes go through service role only (no public write policy)

-- Retrieval RPC ---------------------------------------------------------------
-- Hybrid retrieval with effective-date join + source-tier re-ranking.
-- Caller passes the query embedding and filters; RPC handles the heavy lifting.

create or replace function public.search_ipsas_chunks(
  query_embedding vector(1536),
  pathway_filter text default null,
  jurisdiction_filter text default null,
  exclude_superseded boolean default true,
  match_count integer default 20
)
returns table (
  id uuid,
  standard_id text,
  source_pdf text,
  source_url text,
  page_number integer,
  source_tier integer,
  pathway text,
  jurisdiction_code text,
  text text,
  similarity real
)
language sql
stable
security definer
set search_path = public
as $$
  with candidates as (
    select
      c.id,
      c.standard_id,
      c.source_pdf,
      c.source_url,
      c.page_number,
      c.source_tier,
      c.pathway,
      c.jurisdiction_code,
      c.text,
      1 - (c.embedding <=> query_embedding) as similarity
    from public.ipsas_chunks c
    where
      c.embedding is not null
      and (pathway_filter is null
           or c.pathway = pathway_filter
           or c.pathway = 'both')
      and (jurisdiction_filter is null
           or c.jurisdiction_code is null
           or c.jurisdiction_code = jurisdiction_filter)
      and (
        not exclude_superseded
        or c.standard_id is null
        or not exists (
          select 1
          from public.ipsas_regulation_metadata m
          where m.standard_id = c.standard_id
            and m.status in ('superseded', 'not_yet_effective')
        )
      )
    order by c.embedding <=> query_embedding
    limit greatest(match_count * 3, 60)
  )
  -- Re-rank: boost by source tier (lower tier = higher rank)
  -- final_score = similarity * (1 + (6 - tier) * 0.05)
  -- → tier 1 gets +25%, tier 6 gets +0%
  select
    id, standard_id, source_pdf, source_url, page_number,
    source_tier, pathway, jurisdiction_code, text,
    similarity
  from candidates
  order by similarity * (1.0 + (6 - source_tier) * 0.05) desc
  limit match_count;
$$;

-- Allow approved users (and service role) to call the function
grant execute on function public.search_ipsas_chunks(vector, text, text, boolean, integer)
  to authenticated, service_role;

comment on function public.search_ipsas_chunks is
  'Hybrid IPSAS chunk retrieval with vector similarity + source-tier re-ranking + effective-date filtering. Embedding dim must match text-embedding-3-small (1536).';
